dist: trusty
addons:
  chrome: stable

language: node_js

node_js:
  - 14.2.0

script:
  - npm test --silent

notifications:
  webhooks:
    - https://learn.javascript.ru/taskbook/travis/notifications
